### ISSUE TITLE
setting `world.step(1 / 60)` gives a very slow movement 

### ISSUE THREAD

**Issue by crazyyi** [shakiba/planck.js#11]
Are all the demo setting `world.step(1 / 60)` ?

I use this in my gravity based program and I find the sprite moves very slow. I am using PIXI.js as the renderer and its ticker rate is 60 FPS I believe. If the world time step is unrelated to the frame rate how do I know what time step to use to get a smooth movement?

**Comment by shakiba** [comment]
You can pass elapsed time (in seconds) as second parameter `world.step(hz, dt)`. I guess in you case fps is less than 60, so try `world.step(1/30, dt)`.

**Comment by crazyyi** [comment]
I am currently using this setting and it is moving fast enough but not very natural, but I don't know why.

```
function play(delta) {
	world.step(1 / 30, delta);
       // Update stuff
}

app.ticker.add(function(delta) {
	play(delta * (6 / 60));
})
```

**Comment by shakiba** [comment]
In your code you are effectively passing `delta / 10` to `world.step()`. If delta is in milliseconds you need to pass `delta / 1000`, if it is in seconds just pass `delta`, without `* (6 / 60)`.

**Comment by shakiba** [comment]
I just checked pixi's api doc, can you please try `world.step(1 / 60, app.ticker.elapsedMS / 1000);`.

**Comment by crazyyi** [comment]
It is much slower than just using `world.step(1 / 60)`.

**Comment by shakiba** [comment]
Can you please share a sample code?

**Comment by crazyyi** [comment]
Yes, is there a URL I can link a planck.min.js to CodePen.io? I can link other physics engines to the demo but I can't find planck.js library there.

**Comment by shakiba** [comment]
Yes, it is available on jsdelivr and cdnjs, but I recommend rawgit for testing: https://rawgit.com/shakiba/planck.js/master/dist/planck.js

**Comment by crazyyi** [comment]
OK here is it:
[](https://codepen.io/caymanbruce/pen/XMwGZp?editors=0010)

**Comment by shakiba** [comment]
Cool!

I believe my last comment was correct (`world.step(1 / 60, app.ticker.elapsedMS / 1000);`).

The reason that it is slow in you example is that box2d/planck is designed for metric system and your numbers are too big for metric system. For example, when you add a ball 120 units above a surface, it is like being 120 meters above, and with gravity of 9.8 it takes a while for circle to reach the surface (imagine dropping a ball from top of a 40-story building).

The solution is using smaller numbers for simulation and then scaling them up for rendering.

**Comment by crazyyi** [comment]
But why I can't get a smooth movement using your solution? Have you tried it?

**Comment by shakiba** [comment]
Can you please share your code with my solution again?

**Comment by crazyyi** [comment]
You can just modify the code on codepen.io. It's the same link. I have updated it now.

**Comment by shakiba** [comment]
Your code (same link) does not include my solution, which was using smaller numbers.  I actually was able to do it by setting `app.stage.scale.x = app.stage.scale.y = 10` and then replacing all numbers by one tenth of them. It fixed the the physics, but then pixi rendering didn't look good anymore.

**Comment by crazyyi** [comment]
Weird. I have modified the code already. It's just one line change right?

**Comment by shakiba** [comment]
One line + replacing all geometric numbers.

Maybe you did not save it.

It becomes slow because in your code you remove objects from view, but not from physics.

**Comment by crazyyi** [comment]
Ah I see. But replacing all geometric numbers seem to be a lot of work though. Is there a simpler solution?

**Comment by shakiba** [comment]
It was less than a minute for me! I think it is reasonable to scale UI, not physics.

**Comment by gaurav-dixitv** [comment]
I know this is almost a year old now. But @crazyyi here is the modified code: https://jsfiddle.net/gauravdixitv/xkuyoo14/ (planck.js + pixi). In fact, @shakiba 's solution is the correct way of doing it - scale your rendering, not the physics.
