### ISSUE TITLE
Position takes several steps to update at first

### ISSUE THREAD

**Issue by eiko** [shakiba/planck.js#112]
I have some very simple demo code:

```javascript
const world = planck.World(planck.Vec2(0.0, 0.0));
const body = world.createDynamicBody(planck.Vec2(0.0, 0.0));

// Pixi JS update loop. it basically calls world.step() ~ 60 fps
// frames = ~ 1.0 each frame
app.ticker.add((frames) => {
  world.step(frames / 60);
  body.getPosition().x = Math.random() * 10.0;
  console.log(body.getPosition().x);
});
```

When I run this, it outputs:
```
// => 0.0
// => 0.0
// => 0.0
// => 0.0
// => 0.0
...
// => 7.232817
// => 4.334123
// => 9.1100129
```

The number of steps before it starts updating seems to be based on timestep. I get around 28 frames before it changes when I step(frames / 60) and only 24 frames before it changes when I step (frames / 30).

Any ideas what might be causing this?

**Comment by shakiba** [comment]
The object returned by getPosition() is not supposed to be changed, use body.setPosition(Vec2(x, y)); instead.
