### ISSUE TITLE
Term 'Hz' is incorrect.

### ISSUE THREAD

**Issue by cwgreene** [shakiba/planck.js#12]
In the documentation there are a few references to the variable `hz`

```
 // in each frame call word.step(hz) with fixed frequency
    world.step(1 / 60);
```

And that this variable is the 'frequency'. However, below this we have 1/60. This is not frequency (which is 60 Hz, not 1/60), this is the time step. The example ReadMe should be updated to reflect this.

Also from the source docs:
```
 680 /**
 681  * Take a time step. This performs collision detection, integration, and
 682  * constraint solution.
 683  * 
 684  * Broad-phase, narrow-phase, solve and solve time of impacts.
 685  * 
 686  * @param {float} ts Time step, this should not vary.
 687  * @param {float} dt Elapsed time, since last call.
 688  */
 689 World.prototype.step = function(ts, dt) {
```

**Comment by cwgreene** [comment]
Ah; the call needs to be made with fixed frequency; that is correct. Still, 'Hz' is a misleading variable name.

**Comment by shakiba** [comment]
Yes, it should be 1/hz

**Comment by shakiba** [comment]
I replace `hz` with `1 / hz` in doc, and replace `1 / 60`, for example, with `60` every where it is used.

Please feel free to reopen this issue if you think it is not still correct or clear.
