### ISSUE TITLE
ERROR: npm version of plank.js doesn't works with Typescript

### ISSUE THREAD

**Issue by sermmor** [shakiba/planck.js#121]
Good morning.

Yesterday I was testing a lot of parses or rewrites of Box2D for webs, and I think that Planks.js is the best for the projects that I want to do. But I'm using Typescript and there is an error with the index.d.ts of Planks.js in the npm version uploaded (Plank.js 0.3.12 version): in the line 349 is written:

`p_type: Manifold.Type;`

But It should be without the dot between Manifold and Type:

`p_type: ManifoldType;`

This issue had been corrected in the last github version. Could you upload a new version in npm with the changes?

Thanks!

**Comment by zOadT** [comment]
Sorry for the inconvenience. I'm not a maintainer of the npm package but maybe the temporary workaround in #114 helps

**Comment by shakiba** [comment]
Thanks! I published a new npm version.

**Comment by sermmor** [comment]
Thanks a lot! Now it's works fine. :D
