### ISSUE TITLE
Allowing multiple fixtures

### ISSUE THREAD

**Issue by Siggi005** [shakiba/planck.js#123]
Does this code
```javascript
Body.prototype._addFixture = function(fixture) {
  _ASSERT && common.assert(this.isWorldLocked() == false);

  if (this.isWorldLocked() == true) {
    return null;
  }

  if (this.m_activeFlag) {
    var broadPhase = this.m_world.m_broadPhase;
    fixture.createProxies(broadPhase, this.m_xf);
  }

  fixture.m_next = this.m_fixtureList;
  this.m_fixtureList = fixture;

  // Adjust mass properties if needed.
  if (fixture.m_density > 0.0) {
    this.resetMassData();
  }

  // Let the world know we have a new fixture. This will cause new contacts
  // to be created at the beginning of the next time step.
  this.m_world.m_newFixture = true;

  return fixture
};
```
allow multiple fixtures to be attached to the same body? If not, why not? Is there a workaround?

**Comment by Siggi005** [comment]
I'm very sorry. A very silly error in my code. Thank you for the great Engine!

**Comment by shakiba** [comment]
No worries. That's a private function, probably you want to use createFixture instead.

**Comment by Siggi005** [comment]
Well, I did some trigonometry wrong and created a rectangle with no width. Instead of wondering why the fixture had just the coordinates -1/1, 1/1, 1/-1, -1/-1 I looked up your code to solve my problem. It is working now though, thanks!
