### ISSUE TITLE
RayCast example - gather multiple fixtures crash

### ISSUE THREAD

**Issue by sparecycles** [shakiba/planck.js#13]
## demo freezes at
<img width="560" alt="stopped at multiple raycast" src="https://cloud.githubusercontent.com/assets/719818/24762800/47609d54-1aa4-11e7-982c-64920007b3e8.png">

## with console error
<img width="445" alt="console error: reportFixtureCallback is not a function" src="https://cloud.githubusercontent.com/assets/719818/24762824/5741ee3a-1aa4-11e7-98ce-ffd5a08323cc.png">

clearly, the code at https://github.com/shakiba/planck.js/blob/0024d26/example/RayCast.js#L123 should be
```javascript
    return def;
```

**Comment by shakiba** [comment]
Thank you, fixed it!
