### ISSUE TITLE
World defaults comment docs wrong

### ISSUE THREAD

**Issue by eliasku** [shakiba/planck.js#130]
Very frustrating to search the whole library to resolve why TOI solver eat all your frame time, while you believe you do not set `continuousPhysics` explicitly

```
 * @prop {boolean} [warmStarting = false]
 * @prop {boolean} [continuousPhysics = false]
```
vs
```
warmStarting : true,
continuousPhysics : true,
```

**Comment by shakiba** [comment]
Oh no! Which one should update? It would be great if you make pr.

**Comment by eliasku** [comment]
IMHO comments should be fixed first, or clients will be surprised after update

**Comment by shakiba** [comment]
Great, thanks! I just checked Box2D [code](https://github.com/erincatto/box2d/blob/e94472d3adc6e811f723d48cfd6acacf19fe0b9a/src/dynamics/b2_world.cpp#L54), they are both true by default.
