### ISSUE TITLE
Spread syntax introduced in 0.3.19 breaks old browser support

### ISSUE THREAD

**Issue by ericente** [shakiba/planck.js#134]
Version 0.3.19 appears to be the first to use the spread syntax (...), and I suspect this is what's causing incompatibility between this version and older browsers. 
https://github.com/shakiba/planck.js/commit/32eddf9a64d881658e05975762537b3b87f637af#diff-83c7ea65fda1a6f61c704f578d789d95R7334-R7335

**Comment by shakiba** [comment]
Thanks, fixed!
