### ISSUE TITLE
Error when creating Revolute joint with planck js and phaser 3

### ISSUE THREAD

**Issue by PyChaps** [shakiba/planck.js#142]
Hi, I am new to planck js and one issue that I keep facing is when creating Revolute joints here is my code:
[Planckjs_joint_bug.zip](https://github.com/shakiba/planck.js/files/5122505/Planckjs_joint_bug.zip)

I followed tutorial by Emanuele Feronato: [https://www.emanueleferonato.com/2019/10/12/use-box2d-physics-in-your-phaser-3-projects-with-planck-js-javascript-physics-engine/](url)

And planck js Chain example: [https://piqnt.com/planck.js/Chain](url)

**Can you help me and tell me what I'm doing wrong? Thanks.**

**Comment by shakiba** [comment]
What is the error?

**Comment by PyChaps** [comment]
this:
<img width="262" alt="Screenshot 2020-08-27 at 18 05 59" src="https://user-images.githubusercontent.com/48388239/91467082-5eb3d580-e890-11ea-8e8f-35cd3fd35ace.png">

**Comment by shakiba** [comment]
Ok, so check line 117 of RevoluteJoint, it seems bodyB in undefined.

**Comment by PyChaps** [comment]
Oh, I found the error. I have to return box variable in the createBox function, thank you so much for your time 👍 🥇
