### ISSUE TITLE
Circle WorldManifold normals vs Poly WorldManifold normals (Bug?Question?)

### ISSUE THREAD

**Issue by 2chivi** [shakiba/planck.js#143]
Hey, I noticed collisions between circles result in reverse normals to that of Poly collisions.  I believe there may be a bug, and the distance function simply needs to be reversed in ''getWorldManifold'' for circles.  I think I'm correctly taking into account which fixture is FixtureA and which is FixtureB.

Or maybe I'm misunderstanding something.  Thanks!

**Comment by shakiba** [comment]
Hi, thanks for reporting! It would be great if you make a testbed example to demo the issue and a bug-fix PR.

**Comment by 2chivi** [comment]
My bad, I jumped the gun on this.  I was incorrectly identifying FixtureA vs FixtureB.
