### ISSUE TITLE
Type Error with Shape and BoxShape in TypeScript

### ISSUE THREAD

**Issue by mlg556** [shakiba/planck.js#144]
So, I was getting started with some examples and creating a body with a fixture. The example [HeavyOnLight](https://github.com/shakiba/planck.js/blob/master/example/HeavyOnLight.js) has the code:
```
world.createDynamicBody(Vec2(0.0, 4.5)).createFixture(pl.Circle(0.5), 10.0);
```
since I am using TypeScript, my code is:

```
import pl from 'planck-js'
let world = new pl.World()
world.createBody().createFixture(pl.Box(100, 100))
```

TypeScript underlines the `pl.Box` part and says:
```
No overload matches this call.
  Overload 1 of 3, '(def: FixtureDef): Fixture', gave the following error.
    Argument of type 'BoxShape' is not assignable to parameter of type 'FixtureDef'.
      Type 'BoxShape' is missing the following properties from type 'FixtureDef': shape, userData, friction, restitution, and 5 more.
  Overload 2 of 3, '(shape: Shape, opt?: FixtureOpt | undefined): Fixture', gave the following error.
    Argument of type 'BoxShape' is not assignable to parameter of type 'Shape'.
      Type 'BoxShape' is missing the following properties from type 'Shape': m_type, m_radius, isValid, getRadius, and 7 more.
  Overload 3 of 3, '(shape: Shape, density?: number | undefined): Fixture', gave the following error.
    Argument of type 'BoxShape' is not assignable to parameter of type 'Shape'.
```

What am I doing wrong? It seems that BoxShape should be a child of Shape, but it isn't? How can I add a fixture to a body?

EDIT: this happens with `pl.Circle` too, the error is `Argument of type 'CircleShape' is not assignable to parameter of type 'Shape'.`

I am using `"planck-js": "^0.3.22"` and `"typescript": "^3.9.7"`

**Comment by shakiba** [comment]
@zOadT is our typescript expert! :)

**Comment by zOadT** [comment]
Sorry, this error is on our side. For now you can overwrite your local definition of BoxShape (in `./node_modules/planck-js/lib/shape/index.d.ts`) to:
```
export function BoxShape(hx: number, hy: number, center?: Vec2, angle?: number): BoxShape;
export class BoxShape extends PolygonShape {
  constructor(hx: number, hy: number, center?: Vec2, angle?: number);
  
  // Shape
  /** @internal */ m_type: ShapeType;
  /** @internal */ m_radius: number;

  isValid(shape: any): boolean;
  getRadius(): number;
  getType(): ShapeType;
  getChildCount(): number;
  testPoint(xf: Transform, p: Vec2): false;
  rayCast(output: RayCastOutput, input: RayCastInput, xf: Transform, childIndex?: number): boolean;
  computeAABB(aabb: AABB, xf: Transform, childIndex?: number): void;
  computeMass(massData: MassData, density?: number): void;
  computeDistanceProxy(proxy: DistanceProxy): void;
}
```
(All it does is to add the properties of `Shape` manually to BoxShape) And you would have to do the same with all other shapes. I am trying to find a better solution.

Sorry for the inconvenience :( Please keep this issue open until this is fixed in the typings.

**Comment by mlg556** [comment]
Maybe a solution is to make some of the parameters and methods of `Shape` optional? (like `isValid?(shape: any): boolean;`). Though this would seem to defeat the idea of having a parent class in the first place :)

By the way I have come across a similar issue in the `FixtureOpt` interface: it requires all 8 properties to be implemented, so for example this doesn't work:
```
const bodyOpts: pl.FixtureOpt = { friction: 0.1, density: 3 }
world.createBody().createFixture(pl.Box(100, 100), bodyOpts)
```

should I open another issue?

**Comment by Doeke** [comment]
I think the easiest workaround is as follows:

```js
    const shape = Planck.Circle(Planck.Vec2(0, 0), 2) as unknown as Shape
    this.fixture = this.body.createFixture(shape)
    this.fixture.setSensor(true)
```

**Comment by zOadT** [comment]
Thank you both for your comments!

@mlg556 Yes, this would work. But if you turn on `strictNullChecks` then you would have to check for the existence of `isValid` every time you want to call it, as the types would suggest it may not exists. Currently, it seems to me like we have to bite the bullet and add all inherited methods manually :confused: Except maybe someone has another idea? If not I will create a PR in a few days (but of course you can also create this PR if you want to)
It would be great if you can create an additional issue :)

@Doeke Oh yes, thats a way easier to apply workaround than my was :) Your solution also inspired me to this one:
```
const shape: Shape = <any>planck.Circle(planck.Vec2(0, 0), 2)
```

**Comment by Doeke** [comment]
@zOadT With `any`, ESLint will complain if you use typescript recommended rules (@typescript-eslint/no-explicit-any). Casting to `unknown` is always allowed though.

**Comment by zOadT** [comment]
@Doeke Good point, haven't thought about additional linters

**Comment by Doeke** [comment]
@zOadT I suggest the following fixes:

Use `interface` not `class` in type declarations file:

```js
export interface CircleShape extends Shape {` instead of `export class CircleShape extends Shape {
```

Declare fixture option properties as optional:

```js
export interface FixtureOpt {
  userData?: any;
  friction?: number;
  restitution?: number;
  density?: number;
  isSensor?: boolean;
  filterGroupIndex?: number;
  filterCategoryBits?: number;
  filterMaskBits?: number;
}
```

**Comment by zOadT** [comment]
PR #146 should fix this issue, it applies the suggestion of @Doeke. It would be great if you two could take a quick look at it. Unfortunately the same problems apply to the joint typings. I will fix these later in a separate PR.
