### ISSUE TITLE
How to accelerate the fall of a ball

### ISSUE THREAD

**Issue by h4k1m0u** [shakiba/planck.js#145]
I'm trying to implement a pinball similar to the example provided with planck.js, while using another library (p5.js) for the rendering.
The problem I'm struggling with is that the ball is falling too slowly.

Up till now, I tried increasing the gravity:
```js
    world = new planck.World({
      gravity: planck.Vec2(0, 10),
    });
```

Applying a force (or increasing the speed) and decreasing the density don't result in a fluid ball movement either:

```js
    this.body = world.createDynamicBody({
      position: planck.Vec2(x, y),
      bullet: true,
    });
    this.body.createFixture(
      planck.Circle(this.r),
      {
        density: 1e-3,
        restitution: 0.5,
      },
    );

    // initial force (affects acceleration)
    this.body.applyForceToCenter(planck.Vec2(0, 1e3));
```

Anyone knows how to increase the velocity of a free-falling ball?

**Comment by shakiba** [comment]
What is value of this.r?

**Comment by h4k1m0u** [comment]
I set it to r = 5 so it falls quickly, but it looks too heavy:

[image: Peek 2020-09-24 02-50.gif]

**Comment by shakiba** [comment]
Yes that's too big for 10 g, r=5 is ball with hight 10 meters. Could you set the r to a small number like 0.05 (5cm). Also check out Box2D FAQ for range of numbers that work well.

**Comment by h4k1m0u** [comment]
Perfect, I ended up using a scaling factor = 0.01 to convert from pixels (p5.js) to meters (planck.js), as suggested in Box2D FAQ.
