### ISSUE TITLE
Radial Gravity Support?

### ISSUE THREAD

**Issue by peteringram0** [shakiba/planck.js#15]
Does it support radial gravity? Or have you got an implementation to show for it? Thanks.

**Comment by shakiba** [comment]
Like earth? I think it can be implemented with a joint, similar to mouse or prismatic joint.

**Comment by peteringram0** [comment]
Yer like this: http://www.emanueleferonato.com/2012/03/28/simulate-radial-gravity-also-know-as-planet-gravity-with-box2d-as-seen-on-angry-birds-space/

Does it support everything that box2d supports to achieve this?

**Comment by shakiba** [comment]
Cool!  That was easier than my suggestion.  Yes, it supports everything. You just need to use functions instead of over loaded operators.  For example, instead `vecA = vecB + vecC` use `vecA = Vec2.add(vecB, vecC)`.

**Comment by shakiba** [comment]
I'm going to close this, please feel free to open it again if required.
