### ISSUE TITLE
[question] which box2d version is the current version based on?

### ISSUE THREAD

**Issue by jcyuan** [shakiba/planck.js#154]
box2d c++ version is now v2.4.1.
which box2d c++ version is this lib currently based on?
and how long is the period this lib will sync with the c++ box2d?
thanks!

**Comment by shakiba** [comment]
I don't remember which exact version, I remember it was early 2016.
If you could help with comparing box2d from then with now, we can work together and update planck to match with the new version.

**Comment by jcyuan** [comment]
i would like to help bro, but i'm sorry i'm really not good on math related to physics......  😢
