### ISSUE TITLE
planck.js Typescript definitions lead to many errors with standard examples

### ISSUE THREAD

**Issue by huberv** [shakiba/planck.js#155]
Hi all,
I just set up the plank.js testbed with the 8-balls example from https://piqnt.com/planck.js/8-Ball - however, I used parcel as bundler and typescript. So I'm having the following in my index.ts:

```typescript
import { planck as p } from 'planck-js/dist/planck-with-testbed.commonjs'
import * as pl from 'planck-js'

// From https://piqnt.com/planck.js/8-Ball:
p.testbed('8 Ball', function(testbed) {
    var Vec2 = pl.Vec2, Math = pl.Math;
  
    var SPI4 = Math.sin(Math.PI / 4), SPI3 = Math.sin(Math.PI / 3);
  
    var COLORED = true;
    var BLACK = {fill: 'black', stroke: 'white'};
...
```

This way the example runs fine, but I noticed many typescript errors. I found the following causes:
1. The Shape constructor functions and classes bear the same name, e.g.
```javascript
...
export function CircleShape(radius?: number): CircleShape;
export class CircleShape extends Shape {
  static TYPE: 'circle';
...
```

Somehow the typescript type checker is confused by this (as I am :-)) and at least in one click odyssee Visual Studio code windows crashed, I guess due to a cyclic relationship.

2. Most interfaces declare their props in a mandatory way, such that the typescript type checker doesn't allow partial objects, e.g. due to 
```typescript
export interface FixtureOpt {
  userData: any;
  friction: number;
  restitution: number;
  density: number;
...
```
any object not having e.g. an explicitly defined restitution will lead to a compiler error.

3. Most of the @experiential functions (like Vec2.scaleFn) are not included in the Typescript types

=> Were this conscious "typescript type design decisions" or am I just the first one running into this?
=> Would anyone vote against adjusting the typescript files to resolve these issues? (if I feel like making a PR?)

Thanks!

**Comment by zOadT** [comment]
Thanks for your comments!

1. As far as I know this is supported in Typescript, but it requires a relatively new version. We have to check that 
2. Maybe the typings in the package on npm are outdated? In the repo they are optional (but I have only checked FixtureOpt and BodyDef)
3. Yeah I think they were purposely not included, but I thinks its actually ok to include them. So feel free to add them

**Comment by shakiba** [comment]
Thanks for comments!

I will publish a new npm version, we already update defs to fixed fix 1 and 2.

`@experimental` functions will be removed from the library, so didn't add them to TS to discourage using them.

By the way, why do you need to import twice? Have you tried importing `from 'planck-js/testbed/'`?

**Comment by shakiba** [comment]
I published new npm version, with new ts definition.

**Comment by huberv** [comment]
Hi all, thanks for the comments and updates!

@shakiba Using the single import statement

`import { planck } from 'planck-js/dist/planck-with-testbed.commonjs'`

works, but with just

`import { planck } from 'planck-js/testbed/'`

I get the error

`×...\tinker-planck-js\node_modules\planck-js\testbed\index.js:2:20: Cannot resolve dependency 'stage-js/platform/web'`

If there is a fix for that, I'd be glad!

After updating to the npm package version 0.3.23 the situation looks way better. However, Math.PI and Math.sind seem to be missing in the TS declarations and personally I'd suggest using `@deprecated ` instead of `@experimental`

**Comment by shakiba** [comment]
Ah, I see, would you be able to see if moving stage-js from  devDependencies to dependencies (in package.json) fixes importing issue?

@zOadT any idea about Math?

**Comment by zOadT** [comment]
@shakiba This should work:
```
export let Math: Math & {
  readonly EPSILeON: number;
  /**
   * This function is used to ensure that a floating point number is not a NaN or
   * infinity.
   */
  isFinite(x: any): boolean;
  assert(x: any): void;
  invSqrt(x: number): number;
  nextPowerOfTwo(x: number): number;
  isPowerOfTwo(x: number): boolean;
  mod(num: number, min: number, max: number): number;
  mod(num: number, max?: number): number;
  clamp(num: number, min: number, max: number): number;
  random(min: number, max: number): number;
  random(max?: number): number;
}
```

**Comment by huberv** [comment]
@shakiba Moving stage-js from the devDependencies to the normal dependencies fixes the issue, as does adding and installing stage-js as dependency in my own project (w/o having to tinker with the planck-js package.json file). 

To me it looks like stage-js is only used in the planck js' testbed - therefore I would probably recommend to just document the fact that if you integrate planck-js via npm and want to use the testbed, then you have to add some version of stage-js in your own project. Maybe an alternative could be to add stage-js either as optional or peer dependency for planck-js!?

**Comment by shakiba** [comment]
Ok, great!

Also I have converted builds to umd so commonjs is not needed anymore and will be removed in future.
