### ISSUE TITLE
Adjusting center on a fixture may not be working as intended.

### ISSUE THREAD

**Issue by ChristianTucker** [shakiba/planck.js#158]
**Disclaimer:** I'm fairly new to Box2D so my knowledge of the engine is based on quite a bit of reading on [iForce2D](https://www.iforce2d.net/b2dtut/)
----------

I'm trying to attach a sensor to a body by offsetting the sensors Center in a Fixture as shown in [this Box2D guide](https://www.iforce2d.net/b2dtut/jumpability) however when doing so the center-offset is completely ignored and new objects are added to the center of an object, creating something that looks like this:

![Centering](https://i.imgur.com/8wXSh1X.png)

[Link to Testbed](https://piqnt.com/space/aVtONAfD6)

<details>
  <summary>Sourcecode</summary> 

```js
planck.testbed('GroundSensor', function (testbed) {
    var Edge = planck.Edge, Box = planck.Box, Vec2 = planck.Vec2, Circle = planck.Circle, RevoluteJoint = planck.RevoluteJoint;
    var world = new planck.World(Vec2(0, -9.82));
    
    let edge = world.createBody();
    edge.createFixture(Edge(Vec2(-20, 0), Vec2(20, 0))); 

    let body = world.createDynamicBody();
    body.createFixture(Box(1, 2)); 
    body.setFixedRotation(true); 
    body.setPosition(Vec2(0, 10)); 

    let sensorFixture = body.createFixture(Box(0.6, 0.3), Vec2(0, -2), 0); 
    sensorFixture.setSensor(true); 
    sensorFixture.setUserData('player');https://i.imgur.com/7M8afG6.png
    return world;
});
```
</details>

The way I've found to combat this is using joints, but I feel like this isn't the right way.

![Joints](https://i.imgur.com/7M8afG6.png)

[Link to Testbed](https://piqnt.com/space/MZtut0yrR)

<details>
  <summary>Sourcecode</summary> 

```js
planck.testbed('GroundSensorJoint', function (testbed) {
    var Edge = planck.Edge, Box = planck.Box, Vec2 = planck.Vec2, Circle = planck.Circle, RevoluteJoint = planck.RevoluteJoint;
    var world = new planck.World(Vec2(0, -9.82));
    
    let edge = world.createBody();
    edge.createFixture(Edge(Vec2(-20, 0), Vec2(20, 0))); 

    let body = world.createDynamicBody();
    body.createFixture(Box(1, 2)); 
    body.setFixedRotation(true); 
    body.setPosition(Vec2(0, 10)); 

    let sensor = world.createDynamicBody();
    let sensorFixture = sensor.createFixture(Box(0.6, 0.3)); 
    sensorFixture.setSensor(true); 
    sensorFixture.setUserData('player');
    sensor.setPosition(Vec2(0, 8));

    let joint = RevoluteJoint({}, sensor, body, Vec2(0, 8)); 
    world.createJoint(joint); 

    return world;
});
```
</details>

**Comment by shakiba** [comment]
Fixtures do not have geometry and you need to position shape, so here is the correct code:
```js
body.createFixture(Box(0.6, 0.3, Vec2(0, -2), 0))
```
Note that I'm passing location and angle to `Box` instead of `createFixture`.

**Comment by shakiba** [comment]
By the way, there is a [Discord channel](https://discord.gg/znjh6J7) which is more active than here, if you need faster response please feel free to use it. Also you are making great examples, they may help others learn something new with you.
