### ISSUE TITLE
[Question] Best practices: generating a fixture + static body for in-game text label

### ISSUE THREAD

**Issue by gamecubate** [shakiba/planck.js#18]
A question more than an issue.

If you were to create a game with this lib, how would **generate a fixture for text representation, using an SVG path (of said text string as an outline) as input**?

PS: this project seems to get a lot more attention from its author/maintainer than all others out there; thanks a lot for that. This is much appreciated, given how _not_ easy physics engines are.

**Comment by shakiba** [comment]
Interesting!  If it is *static* (e.g. ground, walls, etc.) and can be represented as polygon (i.e. there is no curve), I would use ChainShape (`planck.Chain(vectorsArray, loop = false)`).

However, it is not possible to create a non-static concave *fixture* or a curved path other than circle.

**Comment by gamecubate** [comment]
So if I understand correctly, I will need to first define 26 coordinate-pair arrays (one per letter of the alphabet), generate 26 (chain?) fixtures from that, and then create a function mapping input string to offset fixtures, wrapping them in a composite body. Should be easy. Thanks a lot for your advice.

**Comment by shakiba** [comment]
Correct, only one thing regarding terminology: you would generate a chain *shape* from each vector array, and create a *fixture* when adding a shape to a body:

```
var shapeA = planck.Edge(vectorsA);
var shapeB = planck.Edge(vectorsB);

var body = world.createBody();
body.createFixture(shapeA);
body.createFixture(shapeB);
```

**Comment by gamecubate** [comment]
Okay. Thanks for the code. Was able to display a rudimentary 'X' with this:
```
      planck.testbed(function(testbed) {
        var pl = planck, Vec2 = pl.Vec2;
        var world = new pl.World(Vec2(0, -10));

        var vectorsA = [Vec2(-10.0, -10.0), Vec2(10.0, 10.0)];
        var vectorsB = [Vec2(-10.0, 10.0), Vec2(10.0, -10.0)];
        var shapeA = planck.Chain(vectorsA, false);
        var shapeB = planck.Chain(vectorsB, false);

        var body = world.createBody({
          type: 'static',
          position: Vec2(0.0, 0.0)
        });
        body.createFixture(shapeA);
        body.createFixture(shapeB);

        return world;
      });
```

Next step: discard the testbed code and add my own (or Pixi's) renderer. Will post in another issue if and when one comes up. Thanks again.
