### ISSUE TITLE
Revolute joint "sticky" on the limits

### ISSUE THREAD

**Issue by joaomacp** [shakiba/planck.js#20]
I'm trying to build a revolute joint that stays at the lower limit if no button is pressed, and rotates to the upper limit when I press a button. The problem is that when the joint is on the limits, it "sticks" to them, and takes a while to start rotating.

[I have built this example on JS Bin](https://jsbin.com/zufezuqidi/edit?html,output)

In the example, the 'up' arrow makes the joint rotate. It responds immediately if it's between the limits, but when it's at the limits it has a delay before it starts moving.

I'm not sure if it's a problem with the library, or if there's a way to code this better so that the issue stops happening.

Thank you

**Comment by shakiba** [comment]
I tested your code with Box2D C++, it reproduced same results, so it is not a planck.js bug. I will try to investigate it further in future to see if it is a expected behavior or not.

You could temporary fix it using following code to change speed:

```js
    if (testbed.activeKeys.up) {
      if (revoluteJoint.getMotorSpeed() > 0) {
        revoluteJoint.m_impulse.z = 0;
        revoluteJoint.setMotorSpeed(-2);
      }

    } else {
      if (revoluteJoint.getMotorSpeed() < 0) {
        revoluteJoint.m_impulse.z = 0;
        revoluteJoint.setMotorSpeed(2);
      }
    }
```

Also, if you are interested to report it to box2d project, here is C++ version of your code:

```cpp
class MyTest : public Test
{
public:
    
	MyTest()
	{
		m_world->SetGravity(b2Vec2(0.0f,0.0f));
		{

			b2BodyDef bd;
			bd.type = b2_dynamicBody;

			b2CircleShape shape;
			shape.m_p.SetZero();

			bd.position = b2Vec2(7.0f, 5.0f);
			bd.fixedRotation = true;
			b2Body* centerBall = m_world->CreateBody(&bd);

			shape.m_radius = 1.0f;
			centerBall->CreateFixture(&shape, 30.0f);


			bd.position = b2Vec2(7.0f, 3.0f);
			bd.fixedRotation = false;
			b2Body* circlingBall = m_world->CreateBody(&bd);

			shape.m_radius = 0.5f;
			circlingBall->CreateFixture(&shape, 2.0f);

			b2RevoluteJointDef rjd;
			rjd.maxMotorTorque = 3500.0f;
			rjd.lowerAngle = -1.5;
			rjd.upperAngle = 1.5;
			rjd.enableLimit = true;
			rjd.enableMotor = true;
			rjd.Initialize(centerBall, circlingBall, b2Vec2(7.0f, 5.0f));

      m_revoluteJoint = (b2RevoluteJoint*)m_world->CreateJoint(&rjd);

			m_revoluteJoint->SetMotorSpeed(3);

		}
	}

  void Keyboard(unsigned char key)
  {
    switch (key)
    {
      case 'a':
        m_revoluteJoint->SetMaxMotorTorque(800.0f);
        m_revoluteJoint->SetMotorSpeed(+2.0f);
        break;

      case 'd':
        m_revoluteJoint->SetMaxMotorTorque(800.0f);
        m_revoluteJoint->SetMotorSpeed(-2.0f);
        break;
    }
  }

	static Test* Create()
	{
		return new MyTest;
	}

  b2RevoluteJoint* m_revoluteJoint;
};

```

**Comment by joaomacp** [comment]
Thank you. The temporary solution works for now. I'll probably report it to the original box2d project later.
