### ISSUE TITLE
applyTorque / applyAngularImpulse not working as expected

### ISSUE THREAD

**Issue by dtgreene** [shakiba/planck.js#204]
I'm not sure this is an actual issue but maybe more of a mis-understanding on my part but I can't seem to get either of the angular methods to have any effect on my bodies.  

[Here's a simple example on codepen](https://codepen.io/dylangggg/pen/wvqKEvo)

Pressing the up arrow applies force which works as expected.  However, pressing left/right to apply torque doesn't seem to have any effect.  I've disabled `fixedRotation` and tweaked angular and linear dampening but still nothing.

Setting the angular velocity directly seems to work okay but that doesn't seem the right way of doing it😕

**Comment by zOadT** [comment]
That is a Problem I also ran into multiple times 😅 You have to specify a density on our fixtures, like e.g.
```JS
lander.createFixture({
	shape: Polygon([
		Vec2(-2, -2),
		Vec2(-2, 2),
		Vec2(-3, 2),
		Vec2(-3, -2)
	]),
	density: 0.1
});
```
I think this is also a behaviour of Box2d, but maybe we should check that

**Comment by dtgreene** [comment]
Woohoo!  Yeah I definitely missed that but I'm glad it works now
