### ISSUE TITLE
When setPosition is called, the ball is suspended in mid-air

### ISSUE THREAD

**Issue by theajack** [shakiba/planck.js#215]
When setPosition is called, the ball is suspended in mid-air

https://piqnt.com/planck.js/Pinball

<img width="782" alt="image" src="https://user-images.githubusercontent.com/23377279/163793191-d9f3a7cf-e2b1-41f1-a563-fbdda54359bd.png">

**Comment by zOadT** [comment]
Hey! Bodies will be set to sleeping if they don't move for some time (this is a an optimization). This should fix it:
```ts
setInterval(() => {
  ball.setPosition(new Vec2(0, 4));
  ball.setAwake(true);
}, 4000)
```

**Comment by theajack** [comment]
Thanks
