### ISSUE TITLE
Revolute joint: misuse or bug?

### ISSUE THREAD

**Issue by gamecubate** [shakiba/planck.js#22]
I have a feeling this is not a bug, yet I remember this not happening in my (looooong ago) tests with Box2D.

When a dynamic body perfectly overlaps another, static one -- their world center coords are same -- and both are joined by a revolute joint (with default jointdef values), it seems that changing world gravity has no effect on the dynamic one; it stays in place, not rotating.

If however I offset one from the other such that they no longer overlap, the dynamic one now responds fluidly to gravity changes.

See this [example](http://alexr.ca/pages/dev/reframe-physics/) .

Does this seem normal to you? Joint friction perhaps? If not, I can test this on another testbed and see what comes up.

**Comment by gamecubate** [comment]
Thinking about this some more made me realize that a compound object was needed here. Closing (non-)issue.

**Comment by shakiba** [comment]
Your example is really cool!  I will add it to a new gallery of examples in near future, or will add it to current demo page.

Also I'm glad you were able to use an alternative renderer.

**Comment by gamecubate** [comment]
Thanks @shakiba .

I coded this in ClojureScript such that I'd be able to define rigs in a syntax like this:
```
(defn rig [w h]
  [
    [:disc "d1" (/ w 2) (/ h 2) 20 {:type :static :angle (u/radians 45)} {:restitution 0.8} {:eye true}]
    [:box  "b1" (/ w 2) (* h 0.25) 20 {:type :dynamic} {:restitution 0.8} {:eye true}]
  ])

(assemble (rig) 100 100 world)
```.
As for the renderer, it's a react-based (re-frame for ClojureScript) SVG.

**Comment by gamecubate** [comment]
Done. I've put the source to the above on [GitHub](https://github.com/gamecubate/re-frame-physics).
