### ISSUE TITLE
Trouble syncing planck.js with custom renderer

### ISSUE THREAD

**Issue by Obobnik** [shakiba/planck.js#220]
**Hi, title probably says it all. For some reason two bodies don't collide when they should. I have two svg rectangles (yes, i use svg for rendering), their positions and dimensions are set in pixels but then i convert it to world coordinates for their "physics bodies" with worldScale of 30 (so 1 meter = 30 pixels). I convert back to pixels and update their positions every frame but when i play it they dont collide when they should be. Pls help me i have no idea what im doing wrong.**

Heres the code as example:
_[example.html.zip](https://github.com/shakiba/planck.js/files/8952458/example.html.zip)_

Thank you very much in advance ❤️.

**Comment by Obobnik** [comment]
Oh, now i see the issue. But i still cannot figure out why are the shapes so offset (using wrong anchor points), i know im doing something wrong but i've been trying to figure it out for like 2 hours but cant seem to fix it. No matter what i do they still use wrong anchor. Can you please look at it again and tell me why is it happening? I would be so grateful ❤️.

(Also thx for the side note, i never really thought about it until now but now i see that it was quite stupid of me to upload files like that).

**Comment by zOadT** [comment]
Oh sorry, I have sent you on the wrong track! An Error in the anchors would have cancelled out here . Actually you just have to half the parameters of the Box contructor:
```javascript
groundCollider.createFixture(pl.Box(parseFloat(ground.getAttribute("width")) / worldScale / 2, parseFloat(ground.getAttribute("height")) / worldScale / 2));
// ...
rectCollider.createFixture(pl.Box(parseFloat(rect.getAttribute("width")) / worldScale / 2, parseFloat(rect.getAttribute("height")) / worldScale / 2));
```
To see why check out [this method](https://github.com/shakiba/planck.js/blob/3b262124cef3559626c825d8073d292c5de2b1d6/src/collision/shape/PolygonShape.ts#L260). Basically, `Box(1, 1)` would have vertices `(1, 1), (-1, 1), (-1, -1), (1, -1)` and would therefore have width and height 2. Hope that helps!

**Comment by Obobnik** [comment]
I tried your solution just now but still no luck with it. I understand why the method works but for some reason visual body of rectangles and their physical bodies are no synced up. Isn't this happening because SVG rectangles have origin in top-left corner (or rather when i pass the SVG element X and Y this position is for top-left corner) and planck.js bodies dont? If not then i really dont understand why it doenst work.

**Comment by zOadT** [comment]
Oh really? Then I have probably changed something else 😅 This is working on my side:
```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <script src="https://cdnjs.cloudflare.com/ajax/libs/planck-js/0.2.7/planck.js" integrity="sha512-4JiVq51x4iADpEfQGRu0ZQxuBesVki6E4Yy45PPRcahnCGnki6s5PgdE2Lf/J/HZpxlgnbR0WMwurV+TN9sz+w==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
</head>
<body>
    <svg width="800" height="600">
        <rect id="rect" x="370" y="100" width="50" height="50"></rect>
        <rect id="ground" x="200" y="400" width="400" height="50"></rect>
    </svg>

    <style>
        svg {
            outline: 2px solid black;
        }
    </style>

    <script>
        // create world
        var pl = planck, Vec2 = pl.Vec2;
        var world = planck.World(planck.Vec2(0, 3));

        // meters to pixels converting constant
        var worldScale = 30;

        //get the two svg shapes
        var ground = document.getElementById("ground");
        var rect = document.getElementById("rect");

        // create ground
        var groundCollider = world.createBody();
        groundCollider.createFixture(pl.Box(parseFloat(ground.getAttribute("width")) / worldScale / 2, parseFloat(ground.getAttribute("height")) / worldScale / 2));
        groundCollider.setPosition(Vec2(parseFloat(ground.getAttribute("x")) / worldScale, parseFloat(ground.getAttribute("y")) / worldScale));
        groundCollider.setUserData(ground);

        // create rectangle
        var rectCollider = world.createBody().setDynamic();
        rectCollider.createFixture(pl.Box(parseFloat(rect.getAttribute("width")) / worldScale / 2, parseFloat(rect.getAttribute("height")) / worldScale / 2));
        rectCollider.setPosition(Vec2(Vec2(parseFloat(rect.getAttribute("x")) / worldScale, parseFloat(rect.getAttribute("y")) / worldScale)));
        rectCollider.setMassData({
            mass : 1,
            center : Vec2(),
            I : 0
        });
        rectCollider.setUserData(rect);

        function loop() {
            world.step(1/60);
            world.clearForces();

            for (var body = world.getBodyList(); body; body = body.getNext()) {
                var bodyPosition = body.getPosition();
                var userData = body.getUserData();

                userData.setAttribute("x", bodyPosition.x * worldScale);
                userData.setAttribute("y", bodyPosition.y * worldScale);
            }

            window.requestAnimationFrame(loop);
        }

        loop();
    </script>
</body>
</html>
```

**Comment by zOadT** [comment]
You are right, but it still works because `Vec2(vec)` just copies `vec`. As long as you don't have to deal with rotations the simplest solution is to update the loop method:
```javascript
function loop() {
    world.step(1/60);
    world.clearForces();

    for (var body = world.getBodyList(); body; body = body.getNext()) {
        var bodyPosition = body.getPosition();
        var userData = body.getUserData();

        userData.setAttribute("x", bodyPosition.x * worldScale - parseFloat(userData.getAttribute('width')) / 2);
        userData.setAttribute("y", bodyPosition.y * worldScale - parseFloat(userData.getAttribute('height')) / 2);
    }

    window.requestAnimationFrame(loop);
}
```
But then the result does not look does not look like the SVG, because the bodies are initialized at the wrong position. To fix this:
```javascript
// create ground
var groundCollider = world.createBody();
groundCollider.createFixture(pl.Box(parseFloat(ground.getAttribute("width")) / worldScale / 2, parseFloat(ground.getAttribute("height")) / worldScale / 2));
groundCollider.setPosition(Vec2(
    (parseFloat(ground.getAttribute("x")) + parseFloat(ground.getAttribute('width')) / 2) / worldScale,
    (parseFloat(ground.getAttribute("y")) + parseFloat(ground.getAttribute('height')) / 2) / worldScale));
groundCollider.setUserData(ground);
// ... (same with rect)
```
You could also just use the `transform` property, but then you would have to also change the x and y value in your SVG (e.g. I think `<rect id="rect" x="370" y="100" width="50" height="50"></rect>` would become `<rect id="rect" x="370" y="100" width="75" height="75" transform="translate(-25 -25)"></rect>` (but you would not have to change your code)

**Comment by Obobnik** [comment]
Omg it actually works, you are my saviour thank you so much for taking the time ❤️.
