### ISSUE TITLE
Simulate different gravity for different bodies?

### ISSUE THREAD

**Issue by quinton-ashley** [shakiba/planck.js#225]
A person on the p5.play discord server asked me this:

```js
// Is there a way to make different objects be affected by gravity in different directions?

// for example:
sprite.gravity.x = -1;
sprite2.gravity.x = 1;
sprite2.gravity.y = 1; 
```

There is no way to do what the student asked in p5.play yet. If I try implementing gravity like this, then when the body hits the floor it jitters around up and down instead of coming to rest. Also the amount of force required is different for objects of different mass.

```js
sprite.body.applyForce({ x: 0, y: 10 }, sprite.body.getWorldCenter());
```

How could I implement the feature the student is suggesting, simulating different gravity on different bodies?

I also noticed bodies have a really high terminal velocity of 120 if you just let them keep falling. How was this number determined? Is there any way to change it? It seems like 40 would be more realistic but I could be wrong.

**Comment by zOadT** [comment]
Hey! After looking at the code in [Solver.ts](https://github.com/shakiba/planck.js/blob/3b262124cef3559626c825d8073d292c5de2b1d6/src/dynamics/Solver.ts#L308) 
```typescript
// Integrate velocities.
v.addMul(h * body.m_gravityScale, gravity);
v.addMul(h * body.m_invMass, body.m_force);
```
I am a bit surprised that the behavior differs. As you see
```typescript
sprite.body.applyForceToCenter(Vec2(0, 10).mul(1 / body.m_invMass), false);
```
should actually do the same as attaching the gravity to the world. Maybe we are just dealing with small objects, therefore the applied force could be too big when not scaled by `1 / body.m_invMass`?

Maybe you could also check if something unexpected happens to body.m_force inside the solver.

**Comment by quinton-ashley** [comment]
worked for me! maybe you forgot to do `sprite.body.m_mass` ?

```js
sprite.body.applyForceToCenter(Vec2(0, 10).mul(sprite.body.m_mass), false);
```

**Comment by zOadT** [comment]
Can you provide an example that shows the jittering on the floor? Would be interested to take a look at it

**Comment by quinton-ashley** [comment]
For sure! Check out this example:
https://editor.p5js.org/quinton-ashley/sketches/ZbkAV-Zj_

The jitter is imperceptible at this scale but for 8-bit style games its visible at lower dimensions.

**Comment by zOadT** [comment]
Thank you for the example! I played around a bit and figured out that you get the exact same result if you just apply a gravity of 20 to the world. So I think the code using `applyForceToCenter` does exactly what we expected but the gravity itself is the problem.
Could it be that the scaling in 8-bit style games result in bodies that are not inside the recommended body size? (https://box2d.org/documentation/index.html#autotoc_md17)

> In particular, Box2D has been tuned to work well with moving shapes between 0.1 and 10 meters.

**Comment by quinton-ashley** [comment]
In p5.play a sprite's physics collider can be accessed using the `body` property. In the example I gave the sprite isn't out of range but it has a width of .45. In the 8 bit example it is out of range though hmm

**Comment by quinton-ashley** [comment]
You're right, just setting the gravity to 20 makes the sprite jitter on the ground. However if I increase the `planck.Settings.velocityThreshold` I can get the box to stop and be at rest. I had changed the velocity threshold to .19 so sprites could move slower than 1.
