### ISSUE TITLE
WheelJoint: how to get anchor position, updated for current bodyB position?

### ISSUE THREAD

**Issue by gamecubate** [shakiba/planck.js#23]
More a question than an issue.

I have 3 fixtures:
- A is a car chassis fixture
- B is a wheel fixture
- C is another wheel fixture

I have 2 wheel joints:
- J1 has its anchor at center of B and axis tied to A.
- J2 has its anchor at center of C and axis tied to A.

Now, I turn on the wheel joint motors. The car moves.

I want to draw each wheel joint's anchor in realtime, as the car moves. To do that, I need to obtain the current world coordinates of body B. Must I keep a ref to B and ask for its world point at each tick, or is there a way to obtain that info with the joint alone (I didn't see a getBodyB function for wheel joints)?

**Comment by shakiba** [comment]
Joint is superclass of WheelJoint and has `getBodyB()`, `WheelJoint#getAnchorB()` may also be useful.

**Comment by gamecubate** [comment]
I had tried WheelJoint@getAnchorB() but IIRC was not getting up to date coordinates, but rather those present at joint creation time. I may be wrong. Will recheck...

**Comment by gamecubate** [comment]
Solved with ```joint > localAnchorA > body.getWorldPoint``` . Here's the [demo](http://alexr.ca/pages/tests/re-frame-physics/) . Closing issue.

**Comment by shakiba** [comment]
That's great! :)
