### ISSUE TITLE
Typo in the Wiki

### ISSUE THREAD

**Issue by LukeD524** [shakiba/planck.js#239]
Noticed a small typo in the wiki, "aetAwake" instead of "setAwake" at [https://github.com/shakiba/planck.js/wiki/World#exploring-the-world](https://github.com/shakiba/planck.js/wiki/World#exploring-the-world)

**Comment by shakiba** [comment]
Oh, thanks! Would you be able to update it?

**Comment by LukeD524** [comment]
I would, but honestly I don't know how🥲

**Comment by shakiba** [comment]
Ah, editing was restricted. I just enabled editing, now you should see an Edit button on top-right.

**Comment by shakiba** [comment]
@LukeD524 Thanks for making the update!
