### ISSUE TITLE
ReferenceError: DEBUG is not defined

### ISSUE THREAD

**Issue by MegaUITeam** [shakiba/planck.js#27]
![image](https://user-images.githubusercontent.com/30184325/29486481-10eea42c-84ef-11e7-98d3-030f2acc6eaf.png)

**Comment by shakiba** [comment]
I don't get it! I can't see anything related to planck.js.

**Comment by BenZed** [comment]
Well, `DEBUG` is globally declared in many files without a keyword.

But I've webpacked planck.js without any difficulty before, so I'm not sure what's happening here. It's almost like he required a specific module directly, in strict mode. 
`const Body = require('plank.js/lib/Body')`, maybe?

in any case, @MegaUITeam, it would help if you gave a better description of what's going on here.

**Comment by shakiba** [comment]
@BenZed Does following helps to fix it?
```
if (typeof DEBUG === 'undefined') { var DEBUG = false; }
```

**Comment by BenZed** [comment]
@shakiba, its @MegaUITeam  that's having the problem!

**plank.js** works fine for me :)

**Comment by shakiba** [comment]
@BenZed I'm glad to hear that! :)  I asked you because you mentioned that the issue may be because of requiting a file directly in strict mode.

**Comment by MegaUITeam** [comment]
![image](https://user-images.githubusercontent.com/30184325/30796719-ffd24586-a1db-11e7-9d9a-c40ade902fbd.png)

**Comment by BenZed** [comment]
@MegaUITeam  Are you requiring modules directly? 

I have a repo that uses webpack and planck.js, and if I import objects from the module in point, this does not happen.
```js
import Body from 'planck.js/lib/Body'
```

vs
```js
import { Body } from 'plank.js' // < causes no problems
```

**Comment by psychobolt** [comment]
I ran into the same problem as @MegaUITeam with bundling planck-js with webpack. Turns out I was guilty of importing in point:
```js
import { Body } from 'planck-js/lib'
```

Following @BenZed example fixes the referenceError.

**Comment by shakiba** [comment]
I change the code, so hopefully this issue is solved. I'm going to close this feel free to open it again if required.
