### ISSUE TITLE
WheelJoint problem

### ISSUE THREAD

**Issue by gearcode** [shakiba/planck.js#28]
I use the WheelJoint  to create a car with suspension.
But when the car tilted and fall down, the wheel will not fixed on  the WheelJoint axis.

<img width="315" alt="wx20170825-114949 2x" src="https://user-images.githubusercontent.com/586033/29698934-a7333452-898b-11e7-9966-ddb377d20da3.png">
<img width="451" alt="wx20170825-115015 2x" src="https://user-images.githubusercontent.com/586033/29698935-a736c982-898b-11e7-80ae-7816b4db8837.png">

Phaser WheelJoint(https://github.com/flyover/box2d.js):
<img width="245" alt="wx20170825-121043 2x" src="https://user-images.githubusercontent.com/586033/29699338-a88a40a4-898e-11e7-8a61-159c229454c9.png">
<img width="276" alt="wx20170825-121116 2x" src="https://user-images.githubusercontent.com/586033/29699339-a88a757e-898e-11e7-91b8-61a5164c321c.png">

[demo.zip](https://github.com/shakiba/planck.js/files/1250762/demo.zip)
[demo_phaser.zip](https://github.com/shakiba/planck.js/files/1250815/demo_phaser.zip)

**Comment by shakiba** [comment]
Interesting!

**Comment by gearcode** [comment]
Is that a BUG?
How can I make this with planck.js?

**Comment by shakiba** [comment]
I will investigate it on weekend, it may be a bug.

**Comment by shakiba** [comment]
I confirm the issue.

**Comment by gearcode** [comment]
Thank you for confirm, 
I hope it can be solved soon.

**Comment by shakiba** [comment]
Finally fixed! :) Thanks for reporting!
