### ISSUE TITLE
Length of DistanceJoint cannot be set through DistanceJointDef

### ISSUE THREAD

**Issue by spinthil** [shakiba/planck.js#31]
Hallo,
I'm using a `DistanceJoint` to attract a `DynamicBody` to a static center `Body`. The original Box2D implementation allows setting the length of the `DistanceJoint` through `DistanceJointDef`. In planck-js the length is automatically calculated as the distance between the two anchors:

`this.m_length = Vec2.distance(anchorB, anchorA);`

Currently I'm overwriting `m_length` after creating the joint. It would be nice if the length could be specified in the definition.

**Comment by shakiba** [comment]
Thanks for reporting the issue!  It would be great if you make a PR to fix it! :)
