### ISSUE TITLE
textures and images on Plank.js

### ISSUE THREAD

**Issue by Cdvalencia** [shakiba/planck.js#37]
Hi, i´ve been trying add images on planks.js, but i colud not make it. i´d like load images through Stage.js and planck-with-testbed to can see rendering images on my canvas. this repository have no examples with images loaders and textures. ¿is it possible, load images and textures on plank.js viewer?

Thanks. your api is amazing.

**Comment by shakiba** [comment]
Hi, thanks!  See this issue: #29

**Comment by Cdvalencia** [comment]
i undertand, but i can create a simples render using  planck-with-testbed, i see it, on that file incluing atlas textures. Exist any example with plank, stage and planck-with-testbed to make use to external images.png, similar to this [example](http://piqnt.com/o/)

**Comment by Cdvalencia** [comment]
My solution was edit the file "planck-with-testbed.js" in the next line (751):

![image](https://user-images.githubusercontent.com/4379656/32877776-1edcb14c-ca71-11e7-83ca-7553fdb426a9.png)
