### ISSUE TITLE
Uncaught TypeError: testbed.play is not a function

### ISSUE THREAD

**Issue by psychobolt** [shakiba/planck.js#40]
Uncaught TypeError: testbed.play is not a function. Got exception when resuming from pause state in testbed.

To reproduce, go to [example](http://piqnt.com/planck.js/Chain) and press 'p' to pause and the again to resume.

In testbed function, [togglePause()](https://github.com/shakiba/planck.js/blob/master/testbed/index.js#L44) play() should be resume().

**Comment by shakiba** [comment]
Thanks @psychobolt ! Please feel free to make a PR to fix it.

**Comment by shakiba** [comment]
Thanks for reporting, it is fixed in new version.
