### ISSUE TITLE
Destroyed Fixture is not removed from Body's fixture list

### ISSUE THREAD

**Issue by psychobolt** [shakiba/planck.js#41]
When I destroy a fixture using body.destroyFixture, I expect the body's fixture list to be updated. 

Expectation: Fixture list without the destroyed fixture. 
Actual: Fixture list includes the destroyed fixture, with null pointer m_next.

Compared to [createFixture](https://github.com/shakiba/planck.js/blob/master/lib/Body.js#L922) function, I do not see m_fixtureList updated in [destroyFixture](https://github.com/shakiba/planck.js/blob/master/lib/Body.js#L947).

**Comment by shakiba** [comment]
Thanks for reporting, I guess it is fixed in v0.1.38, please feel free to reopen if needed.  Also I wonder how you found the issue?  It can help me find and fix similar issue.

**Comment by psychobolt** [comment]
Thanks. 

In my case I developed a UI table that keeps track of the fixture list, so it was empirical in catching the issue.
