### ISSUE TITLE
GearJoint between two PrismaticJoints not working - "Dot is not defined"

### ISSUE THREAD

**Issue by jazzyjeff5** [shakiba/planck.js#45]
I'm finding that a gear joint between two revolute joints works fine, and a gear joint between a revolute and a prismatic work fine* but a gear joint between two prismatic joints causes this:

Uncaught ReferenceError: Dot is not defined
    at GearJoint.solvePositionConstraints (planck.js:9663)
    at Solver.solveIsland (planck.js:3533)
    at Solver.solveWorld (planck.js:3384)
    at World.step (planck.js:4639)

*Only if jointA is the revolute and jointB is the prismatic, not the other way around

Should be simple to reproduce. Thanks for making planck!

**Comment by shakiba** [comment]
Thanks for reporting! I pushed a new update, please try it and let me know if it fixes the issue. If not, can you please share an example so that I can quickly test it?

**Comment by jazzyjeff5** [comment]
Great, thanks! I'll upgrade now and if you don't hear from me assume it's fixed. Another issue before I forget, on line 9380 and 9385 of version 0.1.41, both of those functions have identifier "setRatio", I assume the second one should be "getRatio"? Thanks!

**Comment by shakiba** [comment]
Yes, I fixed it now! :)

**Comment by shakiba** [comment]
I'm closing this, please feel free to reopen it if required.
