### ISSUE TITLE
Optimization Canvas on Cordova

### ISSUE THREAD

**Issue by Cdvalencia** [shakiba/planck.js#48]
Hi Shakiba.

I need know, if exist some library, tool or thecnique that allow me to make optimization with canvas on Cordova. I actually be making a game to android, but my canvas is working so slow. also, i´d want know if this implementation is viable, ¿create a game using plank.js and Stage.js?

Thank´s.

**Comment by shakiba** [comment]
Sorry for delay, almost missed this question. Canvas in most new Android devices is already GPU accelerated, so there is no need to an extra library.

**Comment by Cdvalencia** [comment]
Ok. i'm too clearing the elements that is out of screen. it have imporved my performance.

Thanks for your answer.
