### ISSUE TITLE
Spatial partitioning

### ISSUE THREAD

**Issue by pkieltyka** [shakiba/planck.js#5]
Hey @shakiba - I'm working on an MMO game for the Web, and part of the game design is to use a quad tree on the broadphase for spatial partitioning of events. Effectively a player would only process the physics and network events for near by quads.

I'm still new with working in planck.js, but do you have any suggestions on the right way to connect into the world step to support spatial partitioning in such a way to only process a subset of the world? perhaps bodies remain, but collision detection is reduced to a subset, or perhaps some other ideas for the right approach?

**Comment by shakiba** [comment]
You may be able to use `active` flag of Body for that, see Body#setActive for doc (or just exclude those entities from physics simulation). I also recommend checking out box2d manual, you may find better solutions.

**Comment by shakiba** [comment]
I'm going to close this, please feel free to open it again if required.
