### ISSUE TITLE
Math.isFinite does not exist

### ISSUE THREAD

**Issue by RenaKunisaki** [shakiba/planck.js#50]
In lib/fixture.js:

Fixture.prototype.setDensity = function(density) {
  _ASSERT && common.assert(Math.isFinite(density) && density >= 0.0);
  this.m_density = density;
}

The function is just `isFinite`, not `Math.isFinite`.

**Comment by shakiba** [comment]
Thanks, fixed it! `isFinite` in `common/Math` is a little different.
