### ISSUE TITLE
Typescript @types

### ISSUE THREAD

**Issue by rendaw** [shakiba/planck.js#51]
Would you please publish a types file for Typescript?

**Comment by BenZed** [comment]
You could contribute to the project by making one yourself, @rendaw

**Comment by shakiba** [comment]
Great idea, but I doubt that I would be able to do that anytime soon.

**Comment by zOadT** [comment]
I started writing a definition File over [there](https://github.com/zOadT/planck-typescript/). It's currently a mess because all methods are exposed, so it would be great if some Box2d expert can tell me which methods are private.

**Comment by shakiba** [comment]
@zOadT This is great, thanks for your hard work! Are you interested to add it to planck.js project, so that we can maintain and upgrade it with the project?

**Comment by zOadT** [comment]
Of course! Just give me some time to get it ready over the next weeks.

**Comment by shakiba** [comment]
I released v0.2.1 which includes TS definitions developed by @zOadT. Props to him for the amazing job that he did!
