### ISSUE TITLE
RevoluteJoint.prototype.getReactionForce returns NaN?

### ISSUE THREAD

**Issue by jazzyjeff5** [shakiba/planck.js#52]
Hey,

Trying to get the reaction force and torque out of a joint to determine if I should remove the joint (creating "breakable" joints).

I'm not sure if this code in Planck is correct:

RevoluteJoint.prototype.getReactionForce = function(inv_dt) {
    var P = Vec2.neo(this.m_impulse.x, this.m_impulse.y);
    return inv_dt * P;
};

P is an object with x and y properties, and then the object is multiplied by a number? This returns NaN. Should it be p.mul(inv_dt) instead so the multiplication works correctly?

Thanks!

**Comment by shakiba** [comment]
Probably `Vec2.mul(inv_dt, this.m_impuls)`.

**Comment by shakiba** [comment]
This is fixed in last release.
