### ISSUE TITLE
Y coordinates are displayed off center when using the testbed

### ISSUE THREAD

**Issue by Steveeeie** [shakiba/planck.js#54]
I expected objects to be placed in the center of the screen when placed at 0 on the x and y axes. However this seems to only be the case for x coordinates and not for y coordinates.

![y-position](https://user-images.githubusercontent.com/7037113/39095801-7ccb9554-463e-11e8-84a0-247dbbd12821.jpg)

**Comment by shakiba** [comment]
Testbed y offset is not 0 by default, but you can change it:
```js
planck.testbed('Example', function(testbed) {
  testbed.y = 0;
});
```

**Comment by Steveeeie** [comment]
Excellent, thanks 👍
