### ISSUE TITLE
The performance is worse than box2d.js

### ISSUE THREAD

**Issue by finscn** [shakiba/planck.js#56]
I like planck.js more than box2d.js ,   because the `Motivations` of planck.js.

But I found  the  performance of planck.js is worse than box2d.js

There is a test I created:  

http://fatidol.com/phy-benchmark/

There are many different box2d.js projects  ,  I chose https://github.com/flyover/box2d.js  , 
Because it includes Google's LiquidFun , I like this feature.

**Comment by shakiba** [comment]
Thanks for comparison and feedback!  As far as I know, flyover/box2d.js is JS code included in Google's LiquidFun project, and yes it works better right now. Planck.js still requires more performance optimization which is why it is still alpha version.

**Comment by extremety1989** [comment]
@shakiba have you improoved it ?
