### ISSUE TITLE
PrismaticJoint.prototype.getReactionForce returns NaN

### ISSUE THREAD

**Issue by jazzyjeff5** [shakiba/planck.js#58]
```javascript
PrismaticJoint.prototype.getReactionForce = function(inv_dt) {
   return inv_dt * (this.m_impulse.x * this.m_perp + (this.m_motorImpulse + this.m_impulse.z) * this.m_axis);
};
```

This returns NaN, because this.m_perp and this.m_axis are vectors not numbers. Can't figure out how to fix this myself! Thanks again for all the work you've done on this engine!

**Comment by weilichuang** [comment]
var result = Vec2.zero();
	result.x = inv_dt * (this.m_impulse.x * this.m_perp.x + (this.m_motorImpulse + this.m_impulse.z) * this.m_axis.x);
	result.y = inv_dt * (this.m_impulse.x * this.m_perp.y + (this.m_motorImpulse + this.m_impulse.z) * this.m_axis.y);
	return result;

**Comment by shakiba** [comment]
I fixed this. Thanks for reporting, please feel free to reopen if needed.
