### ISSUE TITLE
Missing documentation

### ISSUE THREAD

**Issue by vndly** [shakiba/planck.js#59]
Where can I find the API documentation? Like the list of main classes and their methods.

**Comment by shakiba** [comment]
There is no doc specific to planck.js, however you can just use Box2D doc and see [this section](https://github.com/shakiba/planck.js#api) for small differences. Also TypeScript definitions are being developed [here](https://github.com/zOadT/planck-typescript/).

**Comment by tomfarnham** [comment]
I get this is an opensource project and just a rewrite of another library, but the lack of documentation on this project is disappointing. Even automatically generated API documentation would be helpful.

**Comment by prettymuchbryce** [comment]
Is providing documentation an explicit non-goal of this project?

If there was enough interest, perhaps the community could slowly build up the documentation over time?

**Comment by shakiba** [comment]
@prettymuchbryce If you are interested please go ahead and add documentation, I and everyone else will appreciate it, and you will own it! I enabled wiki section if you like to use it, we might be able to make a copy of [Box2D docs](https://github.com/erincatto/box2d/tree/master/docs) and adjust it if the license is not different from the code.

**Comment by shakiba** [comment]
A new [api doc](https://github.com/shakiba/planck.js/tree/master/docs) section is available now, it is generated from typescript definitions.

**Comment by shakiba** [comment]
I ported Box2D and added them to the project wiki, I hope it helps.
