### ISSUE TITLE
Export Matrix types

### ISSUE THREAD

**Issue by Reta232** [shakiba/planck.js#68]
## Description

Working on an application in PIXI.js, and the functionality of Mat22 would facilitate some of the translation between the two libraries ( scaling for pixel => meter ).

## Implementation
add the following code to index.js, and define the types in index.d.js

Code:
```javascript
exports.Mat22 = require('./common/Mat22');
```

Type:
```typescript
declare let Mat22: {
	new ( a: number, b: number, c: number, d: number ): Mat22;
	( a: number, b: number, c: number, d: number ): Mat22;

	new (a: { x: number; y: number }, b: { x: number; y: number }): Mat22;
	(a: { x: number; y: number }, b: { x: number; y: number }): Mat22;

	new (): Mat22;
	(): Mat22;

	mul(mx: Mat22, my: Mat22): Mat22;
	mul(mx: Mat22, v: Vec2): Vec2;
	mulT(mx: Mat22, my: Mat22): Mat22;
	mulT(mx: Mat22, v: Vec2): Vec2;
	abs(mx): Mat22;
	add(mx1, mx2): Mat22;
}
```

**Comment by wemyss** [comment]
I'm happy to make a PR for this as it would be useful for me as well. Could also add `Mat33` at the same time.

**Comment by shakiba** [comment]
Sure, sounds good!
