### ISSUE TITLE
[Question] Reasoning behind linked lists in JS

### ISSUE THREAD

**Issue by AlexGustafsson** [shakiba/planck.js#78]
How come you've decided to use linked lists instead of, let's say, arrays?

It seems like a step away from what's usually done in JS. The question came to mind because sometimes it can be a bit awkward to work with linked lists instead of iterable types (general lack of .map, etc.).

Sometimes it's hard to get the right tone across on the internet, so I'm going to be clear here, I'm thoroughly interested and not in any way trying to blame you or the like.

_Note: your code base is very readable and sensible and I applaud you for this. Usually, this type of question would never come to mind since there would be a too large of a hurdle to wrap one's mind around the source, but you've made it easy!_

**Comment by BenZed** [comment]
Not the author, but I imagine he's using linked lists because that's what Box2D uses in C++.

Wherever possible, he wants the API to remain faithful to the Box2D api.

**Comment by shakiba** [comment]
Previous comment is correct, also adding/removing items with linked-list is less problematic. I agree with you that it is a good idea to be able to use array functions.

**Comment by AlexGustafsson** [comment]
Well, I guess my questions has been answered. Thank you both!
