### ISSUE TITLE
Weird issue with DistanceJoint

### ISSUE THREAD

**Issue by dibyendu** [shakiba/planck.js#79]
It's showing unusual behaviour w.r.t distant joint and completely disobeying the constraint apparently.

Here is the small piece of code where it's acting weirdly: https://jsbin.com/civitaqiru/1/edit?html,output

This is what the **ideal** behaviour should be: https://jsbin.com/ziqopamamu/1/edit?html,output

**UPDATE**: even after changing the properties `localAnchorA` and `localAnchorB` to global coordinates (which is counter-intuitively opposite to what the names suggest), although the joint is placed at the correct coordinates, nevertheless the bodies are moving in strange ways: https://jsbin.com/hoyilihanu/edit?html,output

**Comment by shakiba** [comment]
There was an issue in the library that I fixed in v0.3.2, however the main problem was that you set position for fixtures instead of bodies while joints are applied to bodies location. Here is the fix:
https://jsbin.com/ziqayaniyu/edit?html,output
