### ISSUE TITLE
[Question] Proper means of use with NPM installation

### ISSUE THREAD

**Issue by sniggyfigbat** [shakiba/planck.js#83]
This is probably a really stupid question, and certainly shows off my lack of experience with Node, but how do I get Planck to run in a webpage delivered by a Node-based server? I've installed Planck via NPM, but I can't work out how to link the script in correctly.

On likely related topic, when I link Planck in via the CDN, it dies at the first use of _Vec2_ (in the world creation copied from the tutorial) unless I change it to _planck.Vec2_. That would suggest that it's not aliasing object names correctly.

Any help would be much appreciated.

**Comment by sniggyfigbat** [comment]
Right, after much work, I can tell those who come after me that they need to be using Webpack/Browserify/ some other module-to-webcode Node utility. Then it's as 'simple' as reverse-engineering testbed/server.js and package.json. My webpack.config.js ended up looking like [this](https://pastebin.com/qhPXRktt), which I call through 'webpack --config-name static_planck' in the project folder in the command line.

This outputs a nice web-safe, script-includable .js file. Which still doesn't seem to work as the example code on this repo would suggest, because it still wants me to preface Vec2 with the planck namespace. So I have successfully reached the point of badly replicating the CDN.

Still. Progress!

**Comment by shakiba** [comment]
You are right, adding one of those files is enough. All classes are name-spaced to avoid polluting global scope, please feel free to fix Vec2 in tutorial if required.
