### ISSUE TITLE
RevoluteJoint limits not working

### ISSUE THREAD

**Issue by ertdfgcvb** [shakiba/planck.js#9]
It seems like the upperAngle and lowerAngle values don't work: when setting them along with enableLimit the joint won't work anymore.
(Great work on the library, btw!)

**Comment by shakiba** [comment]
Thank you! It should be fixed now, I guess the only problem was #8.

**Comment by ertdfgcvb** [comment]
Hello and thank you…!
But apparently not: I fixed it myself (locally) and the joint doesn't work as expected…
When activating enabling limits it doesn't work at all.

**Comment by shakiba** [comment]
Can you please share your code?

**Comment by ertdfgcvb** [comment]
Sorry! Looks alright now…! Thank you for the fix.

**Comment by shakiba** [comment]
Great, you are welcome!

**Comment by crazyyi** [comment]
@shakiba  Fixed in which version? The current npm package version is 0.1.29, is this fixed in that version?

**Comment by shakiba** [comment]
@crazyyi Just published the new version to npm.
