### ISSUE TITLE
testbed.speed and testbed.hz to 0 dont work as expected

### ISSUE THREAD

**Issue by clankill3r** [shakiba/planck.js#94]
When using:

```
    testbed.speed = 0;
    testbed.hz = 0;
```

I think it would be logical to have the world paused, but instead it just looks like 1.3 and 50.

**Comment by shakiba** [comment]
Can you please try `testbed.pause()` and `testbed.resume()`?

**Comment by shakiba** [comment]
`testbed.speed = 0;` and `testbed.hz = 0;` can only be set when the testbed is being initialized and if they are zero they will fallback to 1 and 60.

**Comment by clankill3r** [comment]
Alright thanks
