### ISSUE TITLE
How can I change Settings.maxPolygonVertices

### ISSUE THREAD

**Issue by clankill3r** [shakiba/planck.js#95]
How can I change `Settings.maxPolygonVertices` (in such a way that it works)  the only thing that worked for me is changing the `planck-with-testbed.js` file, which is a terrible solution...

**Comment by shakiba** [comment]
Can you please try setting `planck.internal.Settings.maxPolygonVertices`?

**Comment by clankill3r** [comment]
That worked, thank you!
